### PR TITLE
Change 'mousemove' to 'pointermove'

### PR DESCRIPTION
**Pull request by nurpais**
I've had some lags when working with sliders, especially when I'm dragging a slider. The lags disappeared when I changed 'mousemove' to 'pointermove'.

There were lags when working with [swiper](https://swiperjs.com/) and [flickity](https://flickity.metafizzy.co/) sliders. I haven't tested it on the other sliders.

https://user-images.githubusercontent.com/25268319/188215522-1e6f42ae-f1d8-4bd5-a619-db67f14bc6d8.mov

https://user-images.githubusercontent.com/25268319/188215531-5e75defd-a239-4926-9300-e0eb1913d863.mov

### CODE REVIEW

**Comment by Drafteed** [comment]
> There were lags when working with [swiper](https://swiperjs.com/) and [flickity](https://flickity.metafizzy.co/) sliders. I haven't tested it on the other sliders.

This happens because these libraries use `mousemove` event and calls `stopPropagation() / preventDefault()`. If they used instead of `pointermove` it would be the same with your changes. 

Possible workaround with Swiper using: 
[touchMoveStopPropagation](https://swiperjs.com/swiper-api#param-touchMoveStopPropagation)
[touchStartPreventDefault](https://swiperjs.com/swiper-api#param-touchStartPreventDefault)
[touchStartForcePreventDefault](https://swiperjs.com/swiper-api#param-touchStartForcePreventDefault)

**Comment by nurpais** [comment]
@Drafteed thank you!

**Comment by ngdot** [comment]
@nurpais , did you get this work on anyway without changing the source code?

**Comment by arnojong** [comment]
@ngdot Adding `touchStartPreventDefault = false` to my (swiper) slider made it work.

**Comment by ngdot** [comment]
@arnojong Can you post your full swiper config? I dont get it work :/

**Pull request closed without merging**
